"""Updated username column

Revision ID: 3a84ecf16e0c
Revises: 0d4edf7aa5a5
Create Date: 2022-10-26 00:12:42.283322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a84ecf16e0c'
down_revision = '0d4edf7aa5a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
